---
title: "Plotly examples"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Examples of plotly

We're gonna look at NYC Airbnb data.

```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```


```{r}
data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(rating = review_scores_location / 2) |>
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) |>
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```

# Plotly plots

## scatterplot

创建一个散点图，每个点代表一个房源，mode = "markers" 指定每个房源显示为一个点。
text = ~text_label: 使用刚刚生成的 text_label 作为每个点的悬浮文本（hover text），在鼠标悬停时显示价格和评分信息。
```{r}
nyc_airbnb |>
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) |>  # "\n"是换行符，把price和rating结合成一个新的标签
  
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",  # 设置 lat 和 long 列为横轴和纵轴的坐标，代表房源的地理位置（经纬度）
    
    color = ~price, text = ~text_label, alpha = 0.5)
```


## boxplot

```{r}
nyc_airbnb |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |>  # fct_reorder用来重新排序因子变量（factor）。具体来说，它按 price 列的数值对 neighbourhood（邻里）列进行排序。
  
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```


## Plotly barchart
```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```


## ggplotly

You can convert a ggplot object straight to an interactive graphic using ggplotly.
```{r}
scatter_ggplot = 
  nyc_airbnb |>
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(alpha = 0.25) +
  coord_cartesian()

ggplotly(scatter_ggplot)
```


